#Variables
@baseUrl = http://localhost:3333

###
#Health Check
# @name getHealth
GET {{baseUrl}}/health

###
#Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###
#Create Rooms
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Teste",
  "description": "Descrição do Teste"
}

###
@roomId = {{createRoom.response.body.$.roomId}}

###
#Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions


###
#Create Questions
# @name createQuestions
POST {{baseUrl}}/rooms/27a9aa11-9396-451c-a061-78e2d3aaa0e3/questions
Content-Type: application/json

{
  "question": "O que é react"
}